restore: ; dotnet restore
build: ; dotnet build --configuration Release --nologo
test: ; dotnet test --configuration Release --nologo --verbosity normal
run: ; dotnet run --project ServiDesk.Api.csproj
