services:
  db:
    image: postgres:16
    container_name: kanban_db
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanbanpw
      POSTGRES_DB: kanban_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
