name: lint
on:
  push:
  pull_request:

jobs:
  super-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Lint codebase
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT_ES: true
