name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    # Do not fail the whole workflow if linters complain
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false  # avoid submodule foreach issues

      - name: Super Linter
        uses: github/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVA: true

          # repo-local rules
          LINTER_RULES_PATH: .
          MARKDOWN_LINTER_RULES: .markdownlint.json
          CSS_LINTER_RULES_PATH: .stylelintrc.json
          JAVACHECKSTYLE_CONFIG_FILE: .github/linters/java_checkstyle.xml

          # ignore bundled static assets
          FILTER_REGEX_EXCLUDE: Advanced/HorizonTicketing/src/main/resources/static/.*
