name: lint
on:
  push:
  pull_request:

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Super Linter (soft-fail)
        uses: github/super-linter@v6
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          OUTPUT_DETAILS: none
          # keep config simple, DO NOT set per-linter VALIDATE_* here
          # use FILTER_REGEX_EXCLUDE to skip big/bundled folders:
          FILTER_REGEX_EXCLUDE: Advanced/HorizonTicketing/src/main/resources/static/.*
